### ISSUE TITLE
ModuleNotFoundError: No module named 'js2py'

### ISSUE THREAD

**Issue by venssy** [sgpublic/xunlei-nastools#5]
已按照git命令拉取所有子模块了，容器启动后third_party下的两个子模块就会被删掉，尝试把third_party映射为只读，直接报chown错误无法启动

```
主机/存储卷 | 容器中的路径
/config/nas-tools | /config
/mnt/video | /video
/config/nas-tools/xunlei-nastools/third_party | /nas-tools/third_party_nas_xunlei
/config/nas-tools/xunlei-nastools/nasxunlei.py | /nas-tools/app/downloader/client/nasxunlei.py
```

```
2024-11-05 23:46:45,638	INFO: 日志输出类型为：console,
2024-11-05 23:46:45,638	INFO: WEB管理页面用户：rosy,
2024-11-05 23:46:45,638	INFO: 未启用https，请使用 http://IP:3000 访问管理页面,
2024-11-05 23:46:45,793	INFO: 数据统计服务启动,
正在加载配置：/config/config.yaml,
正在加载flask环境变量: /nas-tools/.flaskenv,
NAStool 当前版本号：v3.4.1,
开始初始化数据库...,
数据库初始化完成,
开始更新数据库...,
数据库更新完成,
开始初始化数据...,
数据初始化完成,
开始启动服务...,
Traceback (most recent call last):,
  File "/nas-tools/run.py", line 114, in <module>,
    start_service(),
  File "/nas-tools/run.py", line 105, in start_service,
    WebAction.start_service(),
  File "/nas-tools/web/action.py", line 329, in start_service,
    Scheduler(),
  File "/nas-tools/app/utils/commons.py", line 25, in _singleton,
    INSTANCES[cls] = cls(*args, **kwargs),
  File "/nas-tools/app/scheduler.py", line 30, in __init__,
    self.init_config(),
  File "/nas-tools/app/scheduler.py", line 36, in init_config,
    self.run_service(),
  File "/nas-tools/app/scheduler.py", line 73, in run_service,
    self.SCHEDULER.add_job(Rss().rssdownload, 'interval', seconds=pt_check_interval),
  File "/nas-tools/app/utils/commons.py", line 25, in _singleton,
    INSTANCES[cls] = cls(*args, **kwargs),
  File "/nas-tools/app/rss.py", line 34, in __init__,
    self.init_config(),
  File "/nas-tools/app/rss.py", line 38, in init_config,
    self.downloader = Downloader(),
  File "/nas-tools/app/utils/commons.py", line 25, in _singleton,
    INSTANCES[cls] = cls(*args, **kwargs),
  File "/nas-tools/app/downloader/downloader.py", line 54, in __init__,
    self._downloader_schema = SubmoduleHelper.import_submodules(,
  File "/nas-tools/app/helper/submodule_helper.py", line 22, in import_submodules,
    module = importlib.import_module(full_package_name),
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module,
    return _bootstrap._gcd_import(name[level:], package, level),
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import,
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load,
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked,
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked,
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module,
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed,
  File "/nas-tools/app/downloader/client/nasxunlei.py", line 25, in <module>,
    import js2py,
ModuleNotFoundError: No module named 'js2py'
```

**Comment by venssy** [comment]
容器启动失败后，再通过`git submodule update --init --recursive`和`git pull --recurse-submodules`重新拉取子模块，不用重启容器就正常了
